# Generated by Django 5.2.12 on 2026-04-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hod_table_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_table',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
