# Generated by Django 5.2.12 on 2026-04-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_application_table_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation_table',
            old_name='Department',
            new_name='department',
        ),
        migrations.AddField(
            model_name='hod_table',
            name='status',
            field=models.CharField(default='hod', max_length=20),
        ),
        migrations.AddField(
            model_name='student_table',
            name='status',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
