# Generated by Django 5.2.12 on 2026-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_department_allocation_table_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementcell_table',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
