# Generated by Django 5.2.12 on 2026-04-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_placementcell_table_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_table',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
    ]
