# Generated by Django 5.2.12 on 2026-05-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_table_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATTENDWORKSHOP_REQUEST_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table')),
                ('WORKSHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workshop_table')),
            ],
        ),
    ]
