# Generated by Django 5.2.12 on 2026-05-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_attendworkshop_request_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CERTIFICATE_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('certificate', models.FileField(upload_to='')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table')),
                ('WORKSHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workshop_table')),
            ],
        ),
    ]
