# Generated by Django 5.2.12 on 2026-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_certificate_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccancy_table',
            name='JOB',
        ),
        migrations.AddField(
            model_name='vaccancy_table',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccancy_table',
            name='job_details',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JOB_table',
        ),
        migrations.AddField(
            model_name='vaccancy_table',
            name='job',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
