# Generated by Django 5.2.12 on 2026-05-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_vaccancy_table_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMPLAINT_hod_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hod_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table')),
            ],
        ),
    ]
